prefix: "&#249D67&lG&#2BAB72&lI&#31B97C&lV&#38C787&lE&#3ED592&lA&#45E39D&lW&#4BF1A7&lA&#52FFB2&lY&f "
# How often the giveaway message should be broadcasted in seconds (with error margin of 1 minute)
broadcast_interval: 1800
broadcast_message: "%prefix% &fA giveaway is happening on our &#52FFB2Discord&f for %winners% winners to get &#52FFB2%prize%&f! Ends in: &#52FFB2%time_left%&f. Join the &#52FFB2#giveaway&f channel on Discord! [/dc]"

discord:
  bot:
    token: "XXX"
    # ONLINE, IDLE, DND, OFFLINE
    status: ONLINE
    activity: "PLAYING"
    activity_text: "mcgramy.pl"
    activity_url: "https://mcgramy.pl"
    giveaway_channel: XXX
    log_embed_channel: XXX
    command:
      name: "create_giveaway"
      description: "Create a giveaway"
      # Description of the options. The key is the option name, the value is the description
      options:
        name: "Name of the giveaway"
        prize: "Formatted name of the prize"
        minecraft_prize: "Prize in Minecraft format (For broadcast message)"
        duration: "Duration of the giveaway in `Xmo Xd Xh Xm Xs` format"
        winners: "Number of winners"
        command: "First command to execute (%player% is the winner's nick). You can add more in the config.yml"
        requirements: "'true' if there will be requirements added, 'false' or null if not (immediate start)"
    # PLACEHOLDERS: {TIME-LEFT}, {ENTRIES}, {WIN-COUNT}, {PRIZE}, {END-TIME}
    giveaway_embed: |
      {
        "embed": {
          "title": "GIVEAWAY",
          "color": 0xFFFFFF,
          "thumbnail": {
            "url": "https://media.discordapp.net/attachments/1316681865415098368/1335272964131913768/mGiveaway-logo.png?ex=679f915a&is=679e3fda&hm=a8cfa8ba3c69180ce4bce3cb895e4dfd06fd70ae8a4a38993348a3c45dd1b735&=&format=webp&quality=lossless&width=701&height=686"
          },
          "fields": [
            {
              "name": ":clock1: **Time left:**",
              "value": "{TIME-LEFT}",
              "inline": true
            },
            {
              "name": ":family_man_boy_boy: **Entries:**",
              "value": "{ENTRIES}",
              "inline": true
            },
            {
              "name": ":1234: **Winners:**",
              "value": "{WIN-COUNT}",
              "inline": true
            },
            {
              "name": ":trophy: **Prize:**",
              "value": "{PRIZE}",
              "inline": false
            }
          ]
        }
      }
    # PLACEHOLDERS: {TIME-LEFT}, {ENTRIES}, {WIN-COUNT}, {PRIZE}, {END-TIME}
    giveaway_end_embed: |
      { "embed": {
          "title": "GIVEAWAY ENDED",
          "color": 0xFFFFFF,
          "thumbnail": {
              "url": "https://media.discordapp.net/attachments/1316681865415098368/1335272964131913768/mGiveaway-logo.png?ex=679f915a&is=679e3fda&hm=a8cfa8ba3c69180ce4bce3cb895e4dfd06fd70ae8a4a38993348a3c45dd1b735&=&format=webp&quality=lossless&width=701&height=686"
          },
          "fields": [
              {
                  "name": ":family_man_boy_boy: **Entries:**",
                  "value": "{ENTRIES}",
                  "inline": true
              },
              {
                  "name": ":trophy: **Prize:**",
                  "value": "{PRIZE}",
                  "inline": true
              },
              {
                  "name": ":1234: **Winners:**",
                  "value": "{WINNERS}",
                  "inline": false
              }
          ]
      } }

    # PLACEHOLDERS: {GIVEAWAY-NAME}, {ENTRIES-COUNT}, {PRIZE}, {COMMANDS}, {WINNERS-MENTIONS}, {ENTRIES-LIST}
    giveaway_log_embed: |
      {
        "embed": {
          "title": "GIVEAWAY ENDED (LOG)", 
          "color": "0xFFFFFF",
          "fields": [
            {
              "name": ":trophy: **Giveaway:**",
              "value": "**{GIVEAWAY-NAME}** [{ENTRIES-COUNT}]"
            },
            {
              "name": ":gift: **Prize:**",
              "value": "{PRIZE} [{COMMANDS}]" 
            },
            {
              "name": ":busts_in_silhouette: **Winners:**",
              "value": "{WINNERS-MENTIONS}"
            },
            {
              "name": ":clipboard: **Entries:**", 
              "value": "{ENTRIES-LIST}" 
            }
          ],
        }
      }

messages:
  discord:
    embed_title:
      success: "Success!"
      error: "There was an error!"
    giveaway_join:
      already_joined: "You have already joined the giveaway as %player%!"
      nick_already_joined: "This nickname has already joined the giveaway!"
      joined: "You have joined the giveaway as %player%!"
      not_started: "The giveaway has not started yet!"
      already_ended: "The giveaway has already ended!"
    giveaway_command_error:
      no_permission: "You don't have permission to use this command!"
      plugin_paused: "Giveaways are paused! There's a plugin error!"
    giveaway_requirement_error:
      null_player: "**You have never joined the server!**"
      requirements_not_met: "**You do not meet the requirements to enter the giveaway!**\n%requirements%" # %requirements% placeholder for list%requirements% placeholder for list
    giveaway_modal:
      join_modal_title: "Join Giveaway"
      nick_input_question: "Minecraft nickname:"
      nick_input_placeholder: "Your Nickname"
    giveaway_button:
      # PRIMARY, SECONDARY, SUCCESS, DANGER
      join_button_type: PRIMARY
      join_button_text: "Join Giveaway"
      join_button_emoji: "ğŸ‰"
  in_game:
    no_permission: "%prefix% &cYou don't have permission to use this command!"





giveaways:
  5Diamonds:
    settings:
      # Date, when the giveaway should automatically start (not required) [dd/MM/yyyy HH:mm:ss]
      scheduled_start: 31/12/2024 23:59:59
      # Date, when the giveaway should automatically end (required) [dd/MM/yyyy HH:mm:ss]
      end_time: 31/12/2026 23:59:59
      # Number of winners (required)
      winners: 10
      # Commands, which should be executed when the winner applies for his reward (required) [placeholders: %player% - winner's submitted name]
      commands:
        - "give %player% diamond 5"
      # Prize, which will be displayed in the giveaway message (required)
      prize_formatted: "5x Diamond"
      # Placeholder used in the interval broadcast (line 4) (required)
      minecraft_prize: "5 diamonds"
    requirements:
      # User must have VIP but not ADMIN role to join the giveaway (not required)
      group:
        VIP:
          value: true
          # Formatted value of the group, which will be displayed in the giveaway message (not required)
          formatted: "VIP rank"
        ADMIN:
          value: false
          formatted: "no ADMIN rank"
      # Placeholder value of `chatgames_points` must be between 50 and 100 to join the giveaway (not required)
      placeholder:
        chatgames_points:
          formatted: "ChatGames points > 50 and <= 100"
          over: 50
          under: 100
      # User must have permission `mcgramy.giveaway` but not `op` to join the giveaway (not required) [`-` is replaced with `.`]
      permission:
        formatted: "`mcgramy.giveaway` permission and no `op`"
        op: false
        mcgramy-giveaway: true

# DO NOT EDIT THIS VALUE
config_version: 0.5